- name: add microsoft rpm key
  become: yes
  rpm_key:
    state: present
    key: https://packages.microsoft.com/keys/microsoft.asc

- name: add vscode repo
  become: yes
  copy:
    src: vscode.repo
    dest: /etc/yum.repos.d/vscode.repo
    mode: a+r

- name: update dnf cache
  become: yes
  yum:
    update_cache: yes
