- name: add repo keys
  become: yes
  rpm_key:
    key: "{{ item }}"
    state: present
  with_items:
    - "https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-{{ ansible_distribution_major_version }}"

- name: install the rpmfusion rpm from a remote repo
  become: yes
  dnf:
    name: "['https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm',
      'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm']"
    state: present
