- name: install software
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - kile
    - kbibtex

- name: install software
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - texlive-scheme-full
  when:
    - ansible_distribution == "Fedora"

- name: install software
  become: yes
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - texlive-full
  when:
    - ansible_distribution == "Debian"